package org.tests;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.layout.properties.TextAlignment;

import java.io.File;
import java.io.IOException;

public class BankStatementPDFGenerator {

    public static void main(String[] args) throws IOException {
        String outputFile = "Bank_Statement.pdf";
        generateBankStatement(outputFile);
    }

    public static void generateBankStatement(String outputFile) throws IOException {
        // Initialize PDF writer and document
        PdfDocument pdfDoc = new PdfDocument(new com.itextpdf.kernel.pdf.PdfWriter(outputFile));
        Document doc = new Document(pdfDoc);

        // Add Bank Name and Statement Details
        doc.add(new Paragraph("Axis Bank")
                .setFont(PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD))
                .setFontSize(14)
                .setBold()
                .setFontColor(ColorConstants.BLACK));

        doc.add(new Paragraph("Branch: Mumbai Branch")
                .setFont(PdfFontFactory.createFont(StandardFonts.HELVETICA))
                .setFontSize(12));

        doc.add(new Paragraph("Account Holder: Mr. John Doe")
                .setFont(PdfFontFactory.createFont(StandardFonts.HELVETICA))
                .setFontSize(12));

        doc.add(new Paragraph("Account Number: 1234567890")
                .setFont(PdfFontFactory.createFont(StandardFonts.HELVETICA))
                .setFontSize(12));

        doc.add(new Paragraph("Statement Period: 01-Jan-2025 to 31-Jan-2025")
                .setFont(PdfFontFactory.createFont(StandardFonts.HELVETICA))
                .setFontSize(12));

        // Add table headers for transactions
        Table table = new Table(5); // 5 columns for Date, Description, Withdrawals, Deposits, Balance
        table.addHeaderCell("Date");
        table.addHeaderCell("Description");
        table.addHeaderCell("Withdrawals (INR)");
        table.addHeaderCell("Deposits (INR)");
        table.addHeaderCell("Balance (INR)");

        // Add sample transaction rows
        table.addCell("01-Jan-2025");
        table.addCell("Deposit - Salary");
        table.addCell(""); // Withdrawals
        table.addCell("50,000"); // Deposit
        table.addCell("50,000");

        table.addCell("05-Jan-2025");
        table.addCell("ATM Withdrawal");
        table.addCell("5,000");
        table.addCell(""); // Deposit
        table.addCell("45,000");

        table.addCell("10-Jan-2025");
        table.addCell("Online Purchase");
        table.addCell("2,500");
        table.addCell(""); // Deposit
        table.addCell("42,500");

        table.addCell("15-Jan-2025");
        table.addCell("Deposit - Rent");
        table.addCell(""); // Withdrawals
        table.addCell("20,000"); // Deposit
        table.addCell("62,500");

        table.addCell("25-Jan-2025");
        table.addCell("Utility Payment");
        table.addCell("1,000");
        table.addCell(""); // Deposit
        table.addCell("61,500");

        // Add the table to the document
        doc.add(table);

        // Add footer with account holder details
        doc.add(new Paragraph("\n\nGenerated by: Your Application")
                .setFont(PdfFontFactory.createFont(StandardFonts.HELVETICA))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.RIGHT));

        // Close the document
        doc.close();

        System.out.println("Bank Statement PDF generated successfully at: " + outputFile);
    }
}
